### ISSUE TITLE
Unhandled dataset conflicts

### ISSUE THREAD

**Issue by hgray** [aws/aws-sdk-unity#48] opened 2015-04-21 16:26 UTC
It seems there's a way to botch the local database such that it will fail to sync and fail to notify of any failure.

Looking in DefaultDataset around line 463, I see the following:
AmazonLogging.LogError("CognitoSyncManager", "Conflicts detected when pushing changes to remote: " + putRecordsResult.Exception.Message);

This is getting called several times as it does the retry, but when retry drops below zero, no event is fired. Presumably, at the least, it should fire a SyncFailure:
if (--retry<=0){
	FireSyncFailureEvent(putRecordsResult.Exception);
}

However, it would be better if it could fire a conflict event so we could manage the conflict rather than being stuck with a dataset which won't sync.

Thanks

**Comment by albertvaka** [comment] 2015-04-21 21:55
Hi! Thanks for catching the problem. 

There are two things to fix here: first, you should not be in this inconsistent state, and second, we should trigger a failure when we run out of retries. 

The second issue is easy to fix and I'm going to write a patch right away, but for the first one we will need more information. Do you know what led you to this state? Is there a way to reproduce it from scratch? Finally, it would be useful if you can send us the "aws_cognito_cache.db" file where we store the local dataset information, to see what the problem looks like. My email is acintora@amazon.com

Thanks!

**Comment by hgray** [comment] 2015-04-22 01:20
Will do, let me work out the steps.

**Comment by hgray** [comment] 2015-04-23 21:17
Any luck recreating this from the info I emailed?

**Comment by karthiksaligrama** [comment] 2015-05-15 00:41
Fixed in V 2.0.0.0.

**Closed by karthiksaligrama** 2015-05-15 00:41 UTC
