### ISSUE TITLE
No download progress for downloading any object using GetObjectAsync from s3 

### ISSUE THREAD

**Issue by umeraftab** [aws/aws-sdk-unity#98] opened 2015-10-14 12:36 UTC
While downloading any object from s3 using GetObjectAsync method, there should be some track of content downloaded. Why isn't there any way to keep track of download progress?

**Comment by karthiksaligrama** [comment] 2015-10-14 17:38
at the moment there is no feature to track the progress of the download or upload. We are planning to support this in future.

**Comment by karthiksaligrama** [comment] 2015-10-14 19:50
duplicate of #68 , so closing this issue . Please track this feature from #68

**Closed by karthiksaligrama** 2015-10-14 19:50 UTC
