### ISSUE TITLE
I still get empty error message from using Mobile Analytics

### ISSUE THREAD

**Issue by 5argon** [aws/aws-sdk-unity#77] opened 2015-07-27 02:58 UTC
<img width="1118" alt="2015-07-27 11 56 27" src="https://cloud.githubusercontent.com/assets/5653276/8897832/bfed2cd2-3456-11e5-9b73-43f5b00fa343.png">

To reproduce, I just press play on Unity to run a scene with AWSPrefab. Then press stop and press play again you will get this empty message.

**Comment by weijiamao** [comment] 2015-07-29 18:04
Hi, thank you for reporting this issue. Can you tell me your Unity SDK version and Unity version ?

**Comment by weijiamao** [comment] 2015-07-30 20:14
Hi, I cannot reproduce it on Unity SDK 2.0.0.3 and Unity5.1(64bit) on Windows. Can you tell me your SDK version and Unity version ?

**Comment by karthiksaligrama** [comment] 2015-10-14 19:51
Closing issue as not reproducible. Please comment below if you have any updates

**Closed by karthiksaligrama** 2015-10-14 19:51 UTC
Labels: cannot reproduce
