### ISSUE TITLE
SDK 2.0.0 Crashes Unity (on Mac) if the AWSPrefab isn't on the scene

### ISSUE THREAD

**Issue by seaders** [aws/aws-sdk-unity#58] opened 2015-05-15 02:20 UTC
This initially happened after upgrade, because the AWSPrefab had become invalidated so was on the scene just as "Missing".  But after running `new CognitoAWSCredentials(IdentityPoolId, RegionEndpoint.USEast1)`, Unity Editor completely locks up.  If the debugger is connected, you see it's locked up in AWSConfig.unity.cs, line 188 at 'e.WaitOne();'.

If you re-add the prefab, things work as expected.  But after that, if the debugger's connected, the instability that was present for a while pre 2.0.0 seems to be back again.

Hate to be that guy, I've brought this up before, but how much testing do you guys do on Macs?

Specifically with the debugger connected?  If you did, I'm sure you'd see Unity locking up *constantly* when you're doing anything with the AWS library.  It's specifically to do with how the debugger handles signals to and from the Editor on a Mac, and can mess up in background threads, which is obviously what the AWS SDK would be doing.

We at SixMinute have highlighted these types of issues with Unity themselves more than a few times, but this library is something we're building two games on, and want our future games to have too, but it really seems like running it on Mac, with MonoDevelop doesn't seem like it's happening much, or am I wrong?

**Comment by karthiksaligrama** [comment] 2015-05-15 07:30
Thanks for your feedback. We are aware that if aws prefab is not included in the scene then the unity ide can potentially lock up. But due to limitations certain API's on Unity to run only on main thread we are following this design. We have also tried to bring this up on documentation in developer guide and other places.
That said we are open to suggestions on this improving this design. 

About the debugger problem I can confirm that the patch that was made in the previous version has been carried forward to 2.0.0.0 as well. If it still is causing a problem then it seems to be something new. i'll try to reproduce and debug this on mac and will update.

**Comment by seaders** [comment] 2015-05-15 17:50
For debugging, honestly just keep the debugger connected, and start and stop the game, after doing some AWS stuff (Cognito Identiy, Cognito Sync, S3 and DynamoDB).  I can guarantee, without hardly anything else happening, you'll crash within a few minutes.

Again, I've brought this up with Unity themselves already, but even on 5.0.1f1 on a Mac, it's still very much a big bad issue.

**Comment by karthiksaligrama** [comment] 2015-05-15 20:38
Hi,

I tried debugging on a mac with Unity 5.0.1p3. i cant seem to reproduce this problem. I debugged on all services. Is there anything specific that you are trying to do?

**Comment by karthiksaligrama** [comment] 2015-05-19 19:36
Closing this issue as i was not able to reproduce. Please reopen if you feel otherwise.

**Comment by benbritten** [comment] 2015-07-06 08:20
We are getting lockups very similar to this in 5.1.1p2 and 5.1.1p3.  They are very intermittent and I cant reproduce them consistently but unity crashes 6 or 8 times a day. We have the unity initializer script in the scene and hooked up properly but will still get unity locking up. Usually when coming back to Unity from monodevelop.
If we remove AWS from the app entirely then the problem seems to go away, but again it is so intermittent that I cannot say for sure, but i very much sounds like this same issue.

**Comment by benbritten** [comment] 2015-07-09 00:58
So we pulled out all AWS code and have not had a single crash in the last two days. We are going to update to 5.1.1p4 and try it all again, but evidence strongly suggests that there is something going on in the AWS SDK code that is causing the editor to lock up.

**Comment by benbritten** [comment] 2015-07-09 00:59
Also, is it possible to re-open this? Or should I start a new issue?

**Comment by seaders** [comment] 2015-07-09 01:10
I'd also recommend that tbh.  I've recently highlighted that with the call I had with Scott Willeke the other day.  Unfortunately exact steps are difficult to nail down, but the general rule of thumb to ... "feel the pain", is to set up a big-ish project, on a Mac, that has a few different AWS service connections, CognitoIdentity, CognitoSync, S3, DynamoDB, for instance.  Have a scene that sets all those connections up, and uses them in some way.

Then connect the debugger from MonoDevelop and set a few breakpoints, and press play.  Step through some, inspect a few things, continue execution, break, continue execution, break.  Stop the scene, start, repeat.  It won't take 5 starting and stopping before it all crashes up.

**Comment by seaders** [comment] 2015-07-09 01:24
Now, for the initial question of this thread, if you purely change,

        public static bool IsMainThread()
        {
            return Thread.CurrentThread.Equals(_mainThread);
        }

to

        public static bool IsMainThread()
        {
			if(null == _mainThread)
			{
				throw new Exception("Main thread has not been set, is the AWSPrefab on the scene?");
			}
            return Thread.CurrentThread.Equals(_mainThread);
        }

In AWSSDK/src/Core/_unity/UnityInitialiser.cs, that stops the Editor fully locking up / crashing and instead just breaks and throws that error any time any bit of the SDK calls IsMainThread without an AWSPrefab on the screen.  *An infinitely better solution* IMO, than full lockup / crashing.

**Comment by benbritten** [comment] 2015-07-09 01:26
@seaders awesome. thanks for that.

**Comment by weijiamao** [comment] 2015-07-09 22:47
@Seaders: Thank you for your suggestions. Sorry about the bad experience. We are aware of this issue and trying to fix this.

**Comment by seaders** [comment] 2015-07-09 22:57
@weijiamao no problems at all.  I *easily* blame, and communicate with Unity guys as much as ye about these problems, I do know that it's all about the way the debugger connects and operates with Mono on a Mac that causes the problems, but unfortunately, the way the SDK is built with all the threads, they exacerbate the issue and make the lockups & crashing much more likely.

For *this* exact issue, honestly just throwing in the piece of code I've posted, throwing the exception in that call prevents this specific lockup 100%.

I was thinking about a better way to implement it, instead of locking up / throwing an exception, you might think about using the Singleton practise recommended from http://wiki.unity3d.com/index.php/Singleton for the two pivotal guys, UnityInitialiser, and UnityMainThreadDispatcher, and a form of "EnsureInstance" before any sort of network call at all.

Doing that will remove the necessity of responsibility from users from putting it in any scene they want to use and also prevent the lockups.  We've been using it to replace a lot of the forced Prefabs from different plugins & extensions we use, and think it works a lot cleaner than what was around before.

**Comment by benbritten** [comment] 2015-07-09 23:59
It is probably worth noting that we get this lockup without ever using the debugger. Just by going in and out of Unity and changing a script file will cause it. 

Also whenever I see this sort of thing:

#if UNITY_EDITOR
using UnityEditor;
#endif

mixed into runtime code it smells bad to me.

Obviously there are times when you need your code to react properly in edit mode, but generally that is only if you plan to be doing things while the game is not running. For my money, I would rather the AWS SDK not ever do anything at edit time (and if I needed that functionality, I could wrap it up myself). Because right now, the way the code is designed with all the threads, running anything like that in edit mode is a recipe for disaster.

My question is: what IS running in edit mode? and why? and can you take it out, or make it optional?

Also:
I find that using:
if (Application.IsPlaying) {
  Destroy(gameObject);
} else {
  DestroyImmediate(gameObject);
}

to be a cleaner way to handle 'edit time' needs without having to use the dreaded precompiler directives, and if you are doing anything more complicated than that then you should probably have a separate editor script.

**Comment by seaders** [comment] 2015-07-10 00:06
Realistically, the only place I see UNITY_EDITOR code is in UnityInitialiser, and if you look at what it's doing, there's very little going on in there at all, the only thing that changes logic is the gameObject destroy bit you're referencing.

As for it doing stuff in the Editor, with a few tweaks, I've now got the SDK working perfectly in Editor only mode.  Reason for this is for us to view "ghost" runs of players turns in our game.  We're able to list all the ghosts we want from S3, filter them appropriately, then plot their path on the scene...  So there's a few good reasons why it's good that it works there!  I don't think there's millions of custom editor code around, mainly just that UnityInitialiser class.

**Comment by karthiksaligrama** [comment] 2015-07-13 20:34
@seaders @benbritten If it helps i can include the main thread check in the sdk.

About the Editor thing though at this moment i don't have a good enough solution. Personally i would like to get rid of the awsprefab as well. But unity doesn't provide a good way to get access on the mainthread and we need to run some code on the main thread.

**Comment by hgray** [comment] 2015-07-13 21:04
Maybe Amazon can allow us to pass in a GO into the constructor of that Initializer code so we can get rid of the prefab? I've been attaching the script to our own root GO instead of using the prefab for a while.

**Comment by seaders** [comment] 2015-07-14 19:01
@karthiksaligrama It's more slightly concerning that this is closed, and you can't reproduce, tbh.  We're a 10 man studio, all working on Macs, and it happens on every single machine, no deviation.

In AWSConfigs.unity.cs, on line 175, the

    if(UnityInitializer.IsMainThread())

check *always* returns because the UnityInitializer isn't on the scene, and therefore the internal _mainThread is null, so any comparison with it fails.  At the end of the day, this is just plain wrong poor logic no matter what.  Even if this crash isn't happening.  You're checking to see if you're the main thread, but you're using a call where if the setup is incorrect, will always return false.

Because it returns false, in a few lines down, you do,

	ManualResetEvent e = new ManualResetEvent(false);
	UnityRequestQueue.Instance.ExecuteOnMainThread(() =>
        {
		action();
		e.Set();
	});
		
	e.WaitOne();

You think you're not in the main thread when you are, set something to execute on the main thread, then run a WaitOne, locking the thread you're on, the main one.

Hell, just run that code in any script,

	ManualResetEvent e = new ManualResetEvent(false);
	UnityRequestQueue.Instance.ExecuteOnMainThread(() =>
        {
		e.Set();
	});
		
	e.WaitOne();

And you'll lock up Unity's editor 100%.

If you *aren't* getting this lock up, there's something incredibly wrong with your setup, as it is doing exactly what it's programmed to do.  The thing that's wrong is that you think you're not in the main thread when you are, because of how it's set up.

Sample project just to hammer it home, https://github.com/SixMinute/AWSLockup

I've shared this project with a few other Unity people and they can, without doubt, reproduce 100%.  Again, if you can't, run it on a colleagues machine, because there's something wrong with your setup.

**Comment by karthiksaligrama** [comment] 2015-07-14 19:11
If you run 

```
ManualResetEvent e = new ManualResetEvent(false);
UnityRequestQueue.Instance.ExecuteOnMainThread(() =>
    {
    e.Set();
});

e.WaitOne();
```

on Main thread then it will definitely lock up your thread that is the expected behavior because of unity's design to have a single threaded model. 
The above code is meant to run only on background thread. So if you do run any sync API's like say credentials.GetIdentity() it will lock up your unity IDE.

that being said i do think that its better to throw an exception , i will add the check to see if main thread is set or not.

**Comment by seaders** [comment] 2015-07-15 00:23
The reason I was so explicit with my last post is because this issue is titled "SDK 2.0.0 Crashes Unity (on Mac) if the AWSPrefab isn't on the scene", but you've closed it, and marked it "cannot reproduce" which until it's fixed think both are incorrect.  You've just stated that if you run nearly any api calls, it will lock up the Unity IDE.  That's exactly what I said in the first post, and what this thread is about, but again, you closed it and marked it "cannot reproduce".

I'm posting here to ensure other users are also aware of this problem, not least to ask for & wait for a fix from you guys.

**Comment by karthiksaligrama** [comment] 2015-07-15 00:51
Apologies for this. Reopening this and will get this fixed soon. Again sorry for the bad experience.

**Comment by seaders** [comment] 2015-07-15 00:56
Cheers @karthiksaligrama, appreciated.  No need for apologies.

**Comment by karthiksaligrama** [comment] 2015-07-30 19:46
added a mainthread initialized check with version 2.0.0.3

**Closed by karthiksaligrama** 2015-07-30 19:46 UTC
Labels: bug
